services:
  - type: web
    name: yolo-homecage-demo
    env: python
    rootDir: "."            # 明確指定根目錄，確保會讀到 runtime.txt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip check
    startCommand: >
      python -m streamlit run app.py
      --server.port=$PORT
      --server.address=0.0.0.0
    envVars:
      - key: HF_TOKEN_FOR_STREAMLIT
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
