services:
  - type: web
    name: yolo-homecage-demo
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip check
    startCommand: >
      streamlit run app.py
      --server.port=$PORT
      --server.address=0.0.0.0
    envVars:
      # Hugging Face 私有/受保護模型需要的 Token（Railway 介面填值，不要硬編在檔案）
      - key: HF_TOKEN_FOR_STREAMLIT
        sync: false
      # 建議設為 headless 以避免互動提示
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      # 可選：關閉 Streamlit 遙測
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
